import { TranslationKeys, ParametrizedTranslations } from './localization-types';

export const en: TranslationKeys = {
    // Main interface
    plan: 'Development Plan',
    openPlan: 'Open Development Plan',
    inProgress: '🛠️ In Progress',
    inProgressTooltip: 'Current tasks in progress, sorted by due date',
    maxActiveTasksWarning: 'Too many tasks in progress, return some to Planned',
    inProgressStartDate: 'Start Date',
    inProgressDueDate: 'Due Date',
    inProgressOverdue: ' (Overdue!)',
    planned: '⏳ Planned',
    plannedTooltip: 'Planned, but not yet started tasks',
    unknownType: 'Unknown Type',
    unknownSection: 'Unknown Section',
    noTasksForThisType: 'No tasks for this type',
    knowledgeBase: '📚 Knowledge Base',
    knowledgeBaseTooltip: 'Materials for learning, which are not yet detailed',
    knowledgeBaseName: 'Name',
    knowledgeBaseType: 'Type',
    knowledgeBaseSection: 'Section',

    // Export and sources
    exportToJSON: 'Export to JSON',
    exportToJSONTooltip: 'Export the Knowledge Base to a JSON file to share with the community',
    sources: '🔍 Sources',
    sourcesTooltip: 'Resources for filling the Knowledge Base',
    sourceItemsList: 'Source Items',
    sourceItemsExample: '- [ ] Example Source 1\n- [ ] Example Source 2',

    // Statistics and history
    statistics: '📊 Statistics',
    statisticsTooltip: 'Progress analysis by sections',
    history: '🕰️ History',
    historyTooltip: 'Archive of completed tasks, sorted by completion date',
    examples: '📂 Examples',
    examplesTooltip: 'Development plans from the community',

    // Settings
    settingsTitle: 'System Settings',
    generalSettings: 'General Settings',
    materialTypes: 'Material Types',
    sectionsCategories: 'Sections and Categories',
    periodicTasks: 'Periodic Tasks',
    folderPath: 'Folder Path',
    folderPathDesc: 'Folder to store all development plan files (default: PersonalDevelopmentPlan)',
    historyFolderPath: 'History Folder Path',
    historyFolderPathDesc: 'Folder to store history files (default: History)',
    maxActiveTasks: 'Max Active Tasks',
    maxActiveTasksDesc: 'Maximum number of simultaneously active tasks (1-10)',
    statsStartDate: 'Statistics Start Date',
    statsStartDateDesc: 'Start date for statistics collection (format: YYYY-MM-DD)',

    // Item management
    addNewType: '+ New Type',
    newType: 'New Type',
    addNewSection: '+ New Section',
    newSection: 'New Section',
    checklistItem: 'Checklist Item',
    addItem: 'Add Item',
    sectionName: 'Section Name',
    typeName: 'Type Name',
    addTask: '+ Task',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    deleteItem: 'Delete',
    enableDisable: 'Enable/Disable',

    // Periodic tasks
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    dailyTask: 'Daily Task (example)',
    weeklyTask: 'Weekly Task (example)',
    monthlyTask: 'Monthly Task (example)',
    quarterlyTask: 'Quarterly Task (example)',
    yearlyTask: 'Yearly Task (example)',
    errorCreatingPeriodicFile: 'Error creating periodic task file',
    oneTimeTasks: 'One-time Tasks',
    oneTimeTasksExample: 'Example One-time Task',
    dailyTasks: 'Daily Tasks',
    weeklyTasks: 'Weekly Tasks',
    monthlyTasks: 'Monthly Tasks',
    quarterlyTasks: 'Quarterly Tasks',
    yearlyTasks: 'Yearly Tasks',
    week: 'Week',
    month: 'Month',
    quarter: ' quarter',
    quarter1: 'January - March',
    quarter2: 'April - June',
    quarter3: 'July - September',
    quarter4: 'October - December',
    year: 'year',

    // Default material types
    all: 'All',
    book: 'Book',
    bookTask1: 'Read book',
    bookTask2: 'Take notes',
    article: 'Article',
    articleTask1: 'Read',
    articleTask2: 'Extract quotes',
    video: 'Video',
    videoTask1: 'Watch',
    videoTask2: 'Take notes',
    podcast: 'Podcast',
    podcastTask1: 'Listen',
    podcastTask2: 'Take notes',
    course: 'Course',
    courseTask1: 'Complete lesson',
    courseTask2: 'Do assignments',

    // Default sections
    section1: 'General',
    section2: 'Learning',
    section3: 'Work',

    // Default periodic tasks
    periodicTasksDaily1: 'Morning email review',
    periodicTasksDaily2: 'Read a book chapter',
    periodicTasksWeekly1: 'Solve Project Euler problem',
    periodicTasksWeekly2: 'Listen to Culips podcast',
    periodicTasksMonthly1: 'Watch ScalaConf talk video',
    periodicTasksQuarterly1: 'Add ScalaConf recommended books to Knowledge Base',
    periodicTasksYearly1: 'Complete Advanced Scala course',

    // Task creation
    createNewTask: 'Create Task',
    fillRequiredFields: 'Fill in required fields',
    invalidSectionOrType: 'Invalid section or type',
    taskType: 'Task Type',
    invalidTaskType: 'Invalid task type',
    taskCreationError: 'Task creation error',
    selectTaskType: 'Select Task Type',
    untitledTask: 'Untitled Task',
    dontForgetToFillPlan: 'Don\'t forget to fill in the plan!',
    taskOrder: 'Order',
    taskLabel: 'Information',
    laborInputInHours: 'Labor (in hours)',
    taskDefaultDescription: 'Task description',
    checklist: 'Checklist',
    create: 'Create',
    cancel: 'Cancel',
    refreshFailed: 'Refresh failed',

    // New task management translations
    actions: 'Actions',
    addToQueue: 'Add to queue',
    availableOrders: "Available order numbers:",
    noTask: "No task",
    delete: 'Delete',
    planTask: 'Task planning',
    startTask: 'Start task',
    taskPlannedSuccessfully: 'Task successfully planned',
    errorPlanningTask: 'Error planning task',
    confirmDeletion: 'Delete task',
    confirmDeleteTask: 'Are you sure you want to delete task "{taskName}"?',
    taskStartedSuccessfully: 'Task successfully started',
    taskDeletedSuccessfully: 'Task successfully deleted',
    errorStartingTask: 'Error starting task',
    errorDeletingTask: 'Error deleting task',
    dueDateBeforeStartError: 'Due date cannot be before start date',
    dueDateInPastError: 'Due date cannot be in the past',
    save: 'Save',

    // In progress buttons
    completeTask: 'Complete Task',
    taskReview: 'Brief Review',
    taskReviewPlaceholder: 'Describe the results of the task...',
    taskRating: 'Rating',
    completionDate: 'Completion Date',
    complete: 'Complete',
    ratingPoor: 'Poor (does not meet expectations)',
    ratingFair: 'Fair (minimally useful)',
    ratingGood: 'Good (standard quality)',
    ratingVeryGood: 'Very good (above average)',
    ratingExcellent: 'Excellent (exceeded expectations)',
    taskCompletedSuccessfully: 'Task completed successfully',
    errorCompletingTask: 'Error completing task',
    postponeTask: 'Postpone Task',
    confirmPostponeTask: 'Are you sure you want to postpone this task?',
    postpone: 'Postpone',
    taskPostponedSuccessfully: 'Task postponed successfully',
    errorPostponingTask: 'Error postponing task',

    // Filesystem errors
    fileCreationError: 'File creation error',
    fileAlreadyExists: 'File with this name already exists! Change the file name or delete the old one.',
    fileReadError: 'File read error',
    folderCreationError: 'Folder creation error',
    taskCreatedSuccessfully: 'Task created successfully',

    // Material metadata
    authors: 'Authors',
    authorsPlaceholder: 'Enter authors separated by commas',
    bookName: 'Book Name',
    bookNamePlaceholder: 'Enter book name',
    pages: 'Pages',
    pagesPlaceholder: 'Enter number of pages',
    section: 'Section',
    bookContentHeader: '## Description\n\nBrief description of the book content and reading goals\n\n## Progress\n\n',
    articleTitle: 'Article Title',
    articleTitlePlaceholder: 'Enter article title',
    articleUrl: 'Article URL',
    videoTitle: "Video Title",
    videoTitlePlaceholder: "Enter video title",
    videoUrl: "Video URL",
    podcastTitle: "Podcast Title",
    podcastTitlePlaceholder: "Enter podcast title",
    podcastUrl: "Podcast URL",
    courseTitle: "Course Title",
    courseTitlePlaceholder: "Enter course title",
    courseUrl: "Course URL",
    taskTitle: "Task Title",
    taskTitlePlaceholder: "Enter task title",
    author: 'Author',
    authorPlaceholder: 'Enter author',
    platform: 'Platform',
    platformPlaceholder: 'Enter platform',
    durationInMinutes: "Duration (minutes)",
    episodes: "Count of episodes",
    notes: 'Notes',
    addYourThoughts: 'Add your thoughts',

    // Additional
    openSourceError: 'Error opening source code',
    recommendedResources: 'Recommended Resources',
    findAndAddResources: 'Find and add resources',
    personalNotes: 'Personal Notes',
    exportSuccess: 'Export successful',
    exportError: 'Export error',

    // Settings groups
    taskLimit: 'Task Limit',
    startTrackingDate: 'Start Tracking Date',
    customFolder: 'Custom Folder',
    materialTypeSettings: 'Material Types Settings',
    sectionSettings: 'Sections Settings',
    taskSettings: 'Tasks Settings',

    // Statistics
    errorLoadingStatistics: 'Error loading statistics',
    generalStatistics: 'General Statistics',
    totalTasksInPlan: 'Total Tasks',
    contentTypeStatistics: 'Content Type Statistics',
    type: 'Type',
    totalInPlan: 'Total',
    completed: 'Completed',
    completedCount: 'Completed',
    completedTotal: 'Completed total',
    remaining: 'Remaining',
    remainingPages: 'pages',
    remainingHours: 'hours',
    sectionStatistics: 'Section Statistics',

    // Forecast
    forecastTitle: 'Forecast completion',
    forecastMethodology: 'Calculation methodology',
    forecastVisualisation: 'Forecast visualisation',
    forecastCompletion: 'Forecast completion (in days)',
    forecastStartDate: 'Countdown start date (from setting)',
    booksForecastFormula: 'For books: Forecast in days = Remaining pages / Speed in days. Speed in days = Read pages from history / Days passed since start date.',
    otherTypesForecastFormula: 'For other types: Forecast in days = Remaining hours / Speed in days. Speed in days = Completed hours from history / Days passed since start date.',
    optimistic: 'Optimistic forecast in days (-15%)',
    baseForecast: 'Base forecast in days',
    formula: 'Formula',
    pessimistic: 'Pessimistic forecast in days (+15%)',

    // History
    noCompletedTasks: "No completed tasks found",
    errorLoadingHistory: "Error loading history",
    historyFileNotFound: "History file not found",
    historyType: "Type",
    historyTitle: "Title",
    historyStartDate: "Start Date",
    historyCompletionDate: "Completion Date",
    historyWorkingDays: "Working Days",
    historyRating: "Rating",
    historyReview: "Review"
};

export const enParametrized: ParametrizedTranslations = {
    confirmDeleteTask: (params: { taskName: string }) => `Are you sure you want to delete task "${params.taskName}"?`,
    freeOrderAfter: (params: { order: string, taskName: string }) => `Free order ${params.order}, after task: \"${params.taskName}\"`
};
