import { TranslationKeys, ParametrizedTranslations } from './localization-types';

export const en: TranslationKeys = {
    // Main interface
    plan: 'Development plan',
    openPlan: 'Open development plan',
    inProgress: '🛠️ In progress',
    inProgressTooltip: 'Current tasks in progress, sorted by due date',
    maxActiveTasksWarning: 'Too many tasks in progress, return some to Planned',
    inProgressStartDate: 'Start date',
    inProgressDueDate: 'Due date',
    inProgressOverdue: ' (Overdue!)',
    planned: '⏳ Planned',
    plannedTooltip: 'Planned, but not yet started tasks',
    unknownType: 'Unknown type',
    unknownSection: 'Unknown section',
    noTasksForThisType: 'No tasks for this type',
    knowledgeBase: '📚 Knowledge base',
    knowledgeBaseTooltip: 'Materials for learning, which are not yet detailed',
    knowledgeBaseName: 'Name',
    knowledgeBaseType: 'Type',
    knowledgeBaseSection: 'Section',

    // Export and sources
    exportToJSON: 'Export to JSON',
    exportToJSONTooltip: 'Export the knowledge base to a JSON file to share with the community',
    sources: '🔍 Sources',
    sourcesTooltip: 'Resources for filling the knowledge base',
    sourceItemsList: 'Source items',
    sourceItemsExample: '- [ ] Example source 1\n- [ ] Example source 2',

    // Statistics and history
    statistics: '📊 Statistics',
    statisticsTooltip: 'Progress analysis by sections',
    history: '🕰️ History',
    historyTooltip: 'Archive of completed tasks, sorted by completion date',
    examples: '📂 Examples',
    examplesTooltip: 'Development plans that can be used as a basis for your own plan. When imported, new tasks will be added to the existing tasks in the knowledge base',

    // Settings
    settingsTitle: 'System settings',
    generalSettings: 'General settings',
    materialTypes: 'Material types',
    sectionsCategories: 'Sections and Categories',
    periodicTasks: 'Periodic tasks',
    folderPath: 'Folder path',
    folderPathDesc: 'Folder to store all development plan files',
    historyFolderPath: 'History folder Path',
    historyFolderPathDesc: 'Folder to store history files',
    moveToHistory: 'Move completed files to History Folder',
    moveToHistoryDesc: 'When enabled, completed files will be automatically moved to the history folder. When disabled, completed files will be deleted.',
    maxActiveTasks: 'Max active Tasks',
    maxActiveTasksDesc: 'Maximum number of simultaneously active tasks (1-10)',
    statsStartDate: 'Statistics start Date',
    statsStartDateDesc: 'Start date for statistics collection (format: YYYY-MM-DD)',
    cantDeleteTheLast: 'Cannot delete the last item',

    // Item management
    addNewType: '+ New type',
    newType: 'New type',
    addNewSection: '+ New section',
    newSection: 'New section',
    checklistItem: 'Checklist item',
    addItem: 'Add item',
    sectionName: 'Section name',
    typeName: 'Type name',
    addTask: '+ Task',
    moveUp: 'Move up',
    moveDown: 'Move down',
    deleteItem: 'Delete',
    enableDisable: 'Enable/Disable',

    // Periodic tasks
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    dailyTask: 'Daily task (example)',
    weeklyTask: 'Weekly task (example)',
    monthlyTask: 'Monthly task (example)',
    quarterlyTask: 'Quarterly task (example)',
    yearlyTask: 'Yearly task (example)',
    errorCreatingPeriodicFile: 'Error creating periodic task file',
    oneTimeTasks: 'One-time Tasks',
    oneTimeTasksExample: 'Example one-time task',
    dailyTasks: 'Daily tasks',
    weeklyTasks: 'Weekly tasks',
    monthlyTasks: 'Monthly tasks',
    quarterlyTasks: 'Quarterly tasks',
    yearlyTasks: 'Yearly tasks',
    week: 'Week',
    month: 'Month',
    quarter: ' quarter',
    quarter1: 'January - March',
    quarter2: 'April - June',
    quarter3: 'July - September',
    quarter4: 'October - December',
    year: 'year',

    // Default material types
    all: 'All',
    otherTypes: 'Other',
    otherSections: 'Other',
    book: 'Book',
    bookTask1: 'Read book',
    bookTask2: 'Take notes',
    article: 'Article',
    articleTask1: 'Read',
    articleTask2: 'Extract quotes',
    video: 'Video',
    videoTask1: 'Watch',
    videoTask2: 'Take notes',
    podcast: 'Podcast',
    podcastTask1: 'Listen',
    podcastTask2: 'Take notes',
    course: 'Course',
    courseTask1: 'Complete lesson',
    courseTask2: 'Do assignments',

    // Default sections
    section1: 'General',
    section2: 'Learning',
    section3: 'Work',

    // Default periodic tasks
    periodicTasksDaily1: 'Morning email review',
    periodicTasksDaily2: 'Read a book chapter',
    periodicTasksWeekly1: 'Solve project Euler problem',
    periodicTasksWeekly2: 'Listen to Culips podcast',
    periodicTasksMonthly1: 'Watch ScalaConf talk video',
    periodicTasksQuarterly1: 'Add ScalaConf recommended books to the knowledge base',
    periodicTasksYearly1: 'Complete advanced Scala course',

    // Task creation
    createNewTask: 'Create task',
    fillRequiredFields: 'Fill in required fields',
    invalidSectionOrType: 'Invalid section or type',
    taskType: 'Task type',
    invalidTaskType: 'Invalid task type',
    taskCreationError: 'Task creation error',
    selectTaskType: 'Select task Type',
    untitledTask: 'Untitled task',
    dontForgetToFillPlan: 'Don\'t forget to fill in the plan!',
    taskOrder: 'Order',
    taskLabel: 'Information',
    laborInputInHours: 'Labor (in hours)',
    taskDefaultDescription: 'Task description',
    checklist: 'Checklist',
    create: 'Create',
    cancel: 'Cancel',
    refreshFailed: 'Refresh failed',

    // New task management translations
    actions: 'Actions',
    addToQueue: 'Add to queue',
    availableOrders: "Available order numbers:",
    noTask: "No task",
    delete: 'Delete',
    planTask: 'Task planning',
    startTask: 'Start task',
    taskPlannedSuccessfully: 'Task successfully planned',
    errorPlanningTask: 'Error planning task',
    confirmDeletion: 'Delete task',
    confirmDeleteTask: 'Are you sure you want to delete task "{taskName}"?',
    taskStartedSuccessfully: 'Task successfully started',
    taskDeletedSuccessfully: 'Task successfully deleted',
    errorStartingTask: 'Error starting task',
    errorDeletingTask: 'Error deleting task',
    dueDateBeforeStartError: 'Due date cannot be before start date',
    dueDateInPastError: 'Due date cannot be in the past',
    save: 'Save',

    // In progress buttons
    completeTask: 'Complete task',
    taskReview: 'Brief review',
    taskReviewPlaceholder: 'Describe the results of the task...',
    taskRating: 'Rating',
    completionDate: 'Completion date',
    complete: 'Complete',
    ratingPoor: 'Poor (does not meet expectations)',
    ratingFair: 'Fair (minimally useful)',
    ratingGood: 'Good (standard quality)',
    ratingVeryGood: 'Very good (above average)',
    ratingExcellent: 'Excellent (exceeded expectations)',
    taskCompletedSuccessfully: 'Task completed successfully',
    errorCompletingTask: 'Error completing task',
    errorMovingToHistory: 'Failed to move file to history folder',
    postponeTask: 'Postpone task',
    confirmPostponeTask: 'Are you sure you want to postpone this task?',
    postpone: 'Postpone',
    taskPostponedSuccessfully: 'Task postponed successfully',
    errorPostponingTask: 'Error postponing task',

    // Filesystem errors
    fileCreationError: 'File creation error',
    fileAlreadyExists: 'File with this name already exists! Change the file name or delete the old one.',
    fileReadError: 'File read error',
    folderCreationError: 'Folder creation error',
    taskCreatedSuccessfully: 'Task created successfully',

    // Material metadata
    authors: 'Authors',
    authorsPlaceholder: 'Enter authors separated by commas',
    bookName: 'Book name',
    bookNamePlaceholder: 'Enter book name',
    pages: 'Pages',
    pagesPlaceholder: 'Enter number of pages',
    section: 'Section',
    bookContentHeader: '## Description\n\nBrief description of the book content and reading goals\n\n## Progress\n\n',
    articleTitle: 'Article title',
    articleTitlePlaceholder: 'Enter article title',
    articleUrl: 'Article URL',
    videoTitle: "Video title",
    videoTitlePlaceholder: "Enter video title",
    videoUrl: "Video URL",
    podcastTitle: "Podcast title",
    podcastTitlePlaceholder: "Enter podcast title",
    podcastUrl: "Podcast URL",
    courseTitle: "Course title",
    courseTitlePlaceholder: "Enter course title",
    courseUrl: "Course URL",
    taskTitle: "Task title",
    taskTitlePlaceholder: "Enter task title",
    author: 'Author',
    authorPlaceholder: 'Enter author',
    platform: 'Platform',
    platformPlaceholder: 'Enter platform',
    durationInMinutes: "Duration (minutes)",
    episodes: "Count of episodes",
    notes: 'Notes',
    addYourThoughts: 'Add your thoughts',

    // Additional
    openSourceError: 'Error opening source code',
    recommendedResources: 'Recommended resources',
    findAndAddResources: 'Find and add resources',
    personalNotes: 'Personal notes',
    exportSuccess: 'Export successful',
    exportError: 'Export error',

    // Settings groups
    taskLimit: 'Task limit',
    startTrackingDate: 'Start tracking Date',
    customFolder: 'Custom folder',
    materialTypeSettings: 'Material types Settings',
    sectionSettings: 'Sections settings',
    taskSettings: 'Tasks settings',

    // Statistics
    errorLoadingStatistics: 'Error loading statistics',
    generalStatistics: 'General statistics',
    totalTasksInPlan: 'Total tasks',
    contentTypeStatistics: 'Content type Statistics',
    type: 'Type',
    totalInPlan: 'Total',
    completed: 'Completed',
    completedCount: 'Completed',
    completedTotal: 'Completed total',
    remaining: 'Remaining',
    remainingPages: 'pages',
    remainingHours: 'hours',
    sectionStatistics: 'Section statistics',
    noStatisticsAvailable: 'No statistics available',
    noSectionStatistics: 'No section statistics',
    noForecastDataAvailable: 'No forecast data available',

    // Forecast
    forecastTitle: 'Forecast completion',
    forecastMethodology: 'Calculation methodology',
    forecastVisualisation: 'Forecast visualisation',
    forecastCompletion: 'Forecast completion (in days)',
    forecastStartDate: 'Countdown start date (from setting)',
    booksForecastFormula: 'For books: Forecast in days = Remaining pages / Speed in days. Speed in days = Read pages from history / Days passed since start date.',
    otherTypesForecastFormula: 'For other types: Forecast in days = Remaining hours / Speed in days. Speed in days = Completed hours from history / Days passed since start date.',
    baseForecast: 'Base forecast in days',
    formula: 'Formula',
    weekForecast: 'In weeks',
    monthForecast: 'In months',
    yearForecast: 'In years',
    noForecast: 'No enough data to calculate forecast',

    // History
    noCompletedTasks: "No completed tasks found",
    errorLoadingHistory: "Error loading history",
    historyFileNotFound: "History file not found",
    historyType: "Type",
    historyTitle: "Title",
    historyStartDate: "Start date",
    historyCompletionDate: "Completion date",
    historyWorkingDays: "Working days",
    historyRating: "Rating",
    historyReview: "Review",

    // Export
    noExamplePlansAvailable: 'No example plans available',
    planName: 'Plan name',
    description: 'Description',
    import: 'Import',
    exampleImportedSuccessfully: 'Example imported successfully',
    errorImportingExample: 'Error importing example'
};

export const enParametrized: ParametrizedTranslations = {
    confirmDeleteTask: (params: { taskName: string }) => `Are you sure you want to delete task "${params.taskName}"?`,
    freeOrderAfter: (params: { order: string, taskName: string }) => `Free order ${params.order}, after task: \"${params.taskName}\"`
};
